#!/bin/sh

# Nodejs
export PATH=/usr/local/lib/nodejs/bin:$PATH

#udhcpc
mount -a
mount host9p -t 9p /mnt

echo 0 > /proc/sys/kernel/printk

PS1='\W# '
HOME='/root/'

echo
echo "Enable networking using 'udhcpc'"
echo "Files send via emulator appear in /mnt/"

cd ~
