#!/bin/sh

# Nodejs
export PATH=/usr/local/lib/nodejs/bin:$PATH

echo 0 > /proc/sys/kernel/printk

PS1='\W# '
HOME='/root/'

echo
echo "Now - Ready"
echo

# for i in `seq 5`
# do
#     time node --version
# done

unset HISTFILE

cd ~
